"""initial schema

Revision ID: 09aa2b8b54cc
Revises: 
Create Date: 2026-07-01 20:26:28.773640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aa2b8b54cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('massif', sa.String(length=100), nullable=True),
    sa.Column('peak', sa.String(length=200), nullable=True),
    sa.Column('marcaj', sa.String(length=30), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Integer(), nullable=True),
    sa.Column('descent_m', sa.Integer(), nullable=True),
    sa.Column('elev_min_m', sa.Integer(), nullable=True),
    sa.Column('elev_max_m', sa.Integer(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('moving_min', sa.Integer(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('track_json', sa.Text(), nullable=True),
    sa.Column('profile_json', sa.Text(), nullable=True),
    sa.Column('gpx_key', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_slug', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_slug')
    )
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_date'), ['date'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('on_track', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trail_id'], ['trail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('user')
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_date'))

    op.drop_table('trail')
    # ### end Alembic commands ###
